import Head from 'next/head';
import { useNetwork } from '../queries/useNetwork';
import { useAccount, useAccountConnect } from '../queries/useAccount';

export default function Home() {
  const { name: chainName } = useNetwork();
  const address = useAccount();

  const { connect } = useAccountConnect();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{`Hello, ${address}`}</h1>
        <h2>{chainName}</h2>
        {/*{ensName ?? address ? (*/}
        {/*  <button onClick={() => connect(false)}>Disconnect</button>*/}
        {/*) : (*/}
        {/*  <button onClick={() => connect()}>Connect</button>*/}
        {/*)}*/}
      </main>
    </>
  );
}
